
obj-$(CONFIG_LM_PMU) = lm_pmu.o  muxprotocol.o rtc_proto.o ina219_proto.o
obj-$(CONFIG_LM_PMU_SIMPAD) += lm_pmu_sp.o
obj-$(CONFIG_LM_PMU_LINKBOX) += lm_pmu_lb.o

obj-$(CONFIG_LM_PMU_FW) += stm32_core.o stm32_spi.o lm_pmu_fw.o
